### PR TITLE
Add method to fetch individual prices specified by user

### PR DESCRIPTION
**Pull request by cryptopapi997**
Should be pretty straightforward - Lmk if this works and I'll add tests. 
I opted to allow for passing an array of price accounts, as this allows for fetching one price account if needed, but allows for the optimization of using `getMultipleAccountsInfo` under the hood for the case that more than one account is needed.
Also couldn't quite tell from the rest of the library if you guys prefer throwing or returning empty objects (or null or undefined) for invalid data. I opted for throwing for now.

### CODE REVIEW

**Comment by jayantk** [comment]
looks great to me. add a test and i'll approve.

I think throwing makes sense in this context (it suggests a user misconfiguration of the feed ids) so i'm happy with that choice.

**Comment by cryptopapi997** [comment]
Great! Just added tests & removed a duplicate test file you guys still had in there while I was at it

**Comment by cryptopapi997** [comment]
lmk if that works @jayantk

**Comment by jayantk** [comment]
I cut a release with the new functionality as well https://github.com/pyth-network/pyth-client-js/releases/tag/v2.13.0

**Pull request merged**
