### PR TITLE
feat: add types

### PR DESCRIPTION
**Pull request by beautyfree**

### CODE REVIEW

**Comment by beautyfree** [comment]
#2

**Comment by beautyfree** [comment]
#3

**Comment by beautyfree** [comment]
Updated for v2

**Comment by evan-gray** [comment]
@beautyfree Thanks for this and apologies for the delay! Looks like there's some conflicts. Would you be able to resolve them and double-check? Otherwise, I'll try to recreate this later today 🙂

**Comment by beautyfree** [comment]
@evan-gray what conflicts do you mean? 🙂

**Pull request merged**
