### PR TITLE
Add ws support for specific feeds

### PR DESCRIPTION
**Pull request by jacksturt**
Maybe I am using this library wrong, but I could not find a way to only subscribe to specific feeds. This adds support for subscribing to a subset of feeds by providing a list of FeedIds when constructing a PythConnection Object.

### CODE REVIEW

**Comment by jacksturt** [comment]
For reference, I am trying to implement the same charts that Pyth does here: https://pyth.network/price-feeds/crypto-sol-usd?range=1H. I don't see a lot of documentation on how they do this. I am looking in the wrong places, or are these just not documented atm?

**Comment by guibescos** [comment]
Please rebase

**Comment by jacksturt** [comment]
Rebased

**Comment by cryptopapi997** [comment]
Check out https://github.com/pyth-network/pyth-client-js/pull/61 @jacksturt

**Review by jayantk — APPROVED** [review]
thank you!

**Comment by jayantk** [comment]
FYI: I also cut release v2.14.0 with this change included

**Pull request merged**
